const subjects=[
{id:'math',name:'Mathematics',icon:'∑',color:'#6253de',desc:'Numbers, patterns & problem solving'},
{id:'science',name:'Science',icon:'⚗',color:'#0e9a80',desc:'Discover how the world works'},
{id:'social',name:'Social Science',icon:'◎',color:'#d97931',desc:'Our planet, our past & our society'},
{id:'english',name:'English',icon:'Aa',color:'#397fe3',desc:'Read clearly. Write confidently.'},
{id:'hindi',name:'Hindi',icon:'अ',color:'#cf4d82',desc:'भाषा, व्याकरण और अभिव्यक्ति'},
{id:'sanskrit',name:'Sanskrit',icon:'सं',color:'#9470d0',desc:'Build a foundation in संस्कृत'},
{id:'computer',name:'Computer Studies',icon:'⌘',color:'#159bb4',desc:'Digital skills & creative coding'},
{id:'moral',name:'Moral Education',icon:'♡',color:'#c37d23',desc:'Kindness, integrity & thoughtful choices'},
{id:'gk',name:'General Knowledge',icon:'✧',color:'#4f8b54',desc:'Explore India and the wider world'},
{id:'marathi',name:'Marathi',icon:'म',color:'#b25a48',desc:'Optional regional-language foundations'},
{id:'skills',name:'Life & Creative Skills',icon:'✎',color:'#507685',desc:'Art, wellness & financial literacy'}];
const chapters=[];
function add(s,title,rows,task){let id=s+'-'+(chapters.filter(c=>c.subject===s).length+1);chapters.push({id,subject:s,title,concepts:rows.map(r=>({name:r[0],text:r[1],example:r[2],question:r[3],options:r[4],answer:r[5],why:r[6]})),task});}
add('math','Rational Numbers',[
['Parts of a whole','A rational number can be written as p/q, where p and q are integers and q is not zero. Negative fractions are rational too.','A cake cut into 8 equal slices gives 3/8 of a cake when you take 3 slices.','Which is a rational number?',['3/8','5/0','A denominator of zero'],0,'3/8 has integer numerator and non-zero integer denominator.'],
['Equivalent fractions','Multiply or divide the numerator and denominator by the same non-zero number. The value stays the same. Use a common denominator to compare or add.','1/2 = 2/4. Half a pizza is still half, even if you cut each piece again.','1/2 + 1/4 is …',['2/6','3/4','1/8'],1,'Rewrite 1/2 as 2/4, then add: 2/4 + 1/4 = 3/4.'],
['Signed arithmetic','For addition, move right on a number line for a positive number and left for a negative number. Multiplying two negatives gives a positive.','A temperature of −3°C rises by 5°C: −3 + 5 = 2°C.','What is (−2) × (−3)?',['−6','−1','6'],2,'The product of two negative numbers is positive: 2 × 3 = 6.']
],'Draw a number line from −2 to 2 and mark −3/2, −1/2 and 3/2. Explain which is greatest.');
add('math','Fractions & Decimals',[
['Place value','Digits after the decimal represent tenths, hundredths and thousandths. Align decimal points when adding or subtracting.','₹12.50 + ₹3.75 = ₹16.25. Write both amounts in aligned columns.','0.7 + 0.25 equals …',['0.32','0.95','0.725'],1,'0.70 + 0.25 = 0.95.'],
['Multiplying fractions','Multiply the numerators and multiply the denominators, then simplify. “Of” often means multiplication.','Half of 3/4 litre is 1/2 × 3/4 = 3/8 litre.','1/2 of 3/4 is …',['3/8','4/6','3/2'],0,'Multiply: (1 × 3)/(2 × 4) = 3/8.'],
['Dividing fractions','To divide by a non-zero fraction, multiply by its reciprocal. The reciprocal of 2/3 is 3/2.','How many half-litre bottles fill 3 litres? 3 ÷ 1/2 = 3 × 2 = 6.','3 ÷ 1/2 equals …',['1.5','3.5','6'],2,'Each litre contains two half-litres, so 3 litres contain 6.']
],'Calculate the cost of 2.5 kg of rice priced at ₹48 per kg. Show each step.');
add('math','Integers & Operations',[
['Positive and negative','Integers include negative whole numbers, zero and positive whole numbers. On a number line, numbers farther right are greater.','A lift on floor −2 is below floor 1.','Which is greater?',['−5','−2','They are equal'],1,'−2 is to the right of −5 on the number line.'],
['Subtracting integers','Subtracting a number means adding its opposite: a − b = a + (−b).','5 − (−2) = 5 + 2 = 7.','5 − (−2) equals …',['3','−7','7'],2,'Subtracting a negative becomes addition.'],
['Order of operations','Evaluate brackets first, then powers, then multiplication/division from left to right, then addition/subtraction from left to right.','2 + 3 × 4 = 2 + 12 = 14.','2 + 3 × 4 equals …',['20','14','24'],1,'Multiplication happens before addition.']
],'Create a 5-step temperature story with positive and negative changes. Find the final temperature.');
add('math','Exponents & Powers',[
['Repeated multiplication','aⁿ means multiply a by itself n times. a is the base and n is the exponent; it does not mean a × n.','2⁴ = 2 × 2 × 2 × 2 = 16.','What is 2⁴?',['8','16','6'],1,'Four factors of 2 give 16.'],
['Same-base rules','aᵐ × aⁿ = aᵐ⁺ⁿ. For non-zero a, aᵐ ÷ aⁿ = aᵐ⁻ⁿ. Keep the base unchanged.','2³ × 2² = 2⁵ = 32.','3² × 3³ equals …',['3⁶','6⁵','3⁵'],2,'Add the exponents for multiplication with the same base.'],
['Zero exponent','Any non-zero number raised to power zero is 1. This follows by dividing equal powers.','5³ ÷ 5³ = 1 = 5⁰.','7⁰ equals …',['1','0','7'],0,'A non-zero base to power zero is 1.']
],'Write 64 in three different ways using powers with whole-number bases.');
add('math','Percentages & Their Applications',[
['Out of one hundred','Percent means per hundred. Convert a fraction to a percent by multiplying by 100.','18 correct out of 20 = 18/20 × 100 = 90%.','18 out of 20 is …',['18%','90%','80%'],1,'18/20 = 0.9, so the percentage is 90%.'],
['Discount and profit','Discount is a reduction in marked price. Profit = selling price − cost price. Profit percentage uses cost price as the base.','A ₹500 bag at 20% discount costs 500 − 100 = ₹400.','20% off ₹500 gives a price of …',['₹480','₹100','₹400'],2,'Discount = 20/100 × 500 = ₹100; pay ₹400.'],
['Simple interest','Simple interest = principal × rate × time / 100, when rate is yearly and time is in years. Amount = principal + interest.','₹1,000 at 5% per year for 2 years earns ₹100 simple interest.','Simple interest on ₹1,000 at 5% for 2 years?',['₹100','₹50','₹1,100'],0,'1000 × 5 × 2 / 100 = ₹100. ₹1,100 is the amount.']
],'Compare a ₹800 item with 25% off and a ₹700 item with 10% off. Which costs less?');
add('math','Algebraic Expressions',[
['Variables and terms','A variable is a symbol for a changing or unknown value. Terms are separated by addition or subtraction. A coefficient multiplies a variable.','If one notebook costs x rupees, 3 notebooks cost 3x.','In 3x + 5, the coefficient of x is …',['5','3','x'],1,'3 multiplies x, so 3 is its coefficient.'],
['Like terms','Like terms have exactly the same variable part. Add their coefficients. Unlike terms cannot be combined this way.','3x + 2x = 5x, but 3x + 2y remains 3x + 2y.','3x + 2x is …',['5x','5x²','6x'],0,'Add the coefficients: 3 + 2 = 5.'],
['Substitution','Replace each variable with its given value, then follow the order of operations.','For x = 4, 2x + 3 = 2 × 4 + 3 = 11.','If x = 4, 2x + 3 equals …',['14','9','11'],2,'Multiply 2 by 4, then add 3.']
],'Write an expression for the cost of n pens at ₹8 each plus one ₹30 notebook. Evaluate it for n = 5.');
add('math','Linear Equations in One Variable',[
['Balance','An equation says two expressions are equal. Keep it balanced by doing the same operation to both sides.','x + 5 = 12. Subtract 5 from both sides: x = 7.','Solve x + 5 = 12.',['x = 17','x = 7','x = 5'],1,'Subtracting 5 from each side gives x = 7.'],
['Undo multiplication','If a variable is multiplied by a non-zero number, divide both sides by that number. Check by substitution.','3x = 18 ⇒ x = 6. Check: 3 × 6 = 18.','Solve 3x = 18.',['6','15','54'],0,'Divide both sides by 3.'],
['Two steps','Undo addition/subtraction first, then multiplication/division.','2x + 3 = 11 ⇒ 2x = 8 ⇒ x = 4.','Solve 2x + 3 = 11.',['7','8','4'],2,'Subtract 3 and then divide by 2.']
],'Three identical notebooks and a ₹10 pen cost ₹100. Form and solve an equation for a notebook’s price.');
add('math','Angles & Parallel Lines',[
['Angle pairs','Complementary angles total 90°. Supplementary angles total 180°. A linear pair is supplementary.','An angle of 35° needs 55° to make a right angle.','The complement of 35° is …',['145°','55°','65°'],1,'90 − 35 = 55°.'],
['Vertically opposite angles','When two straight lines cross, the angles opposite each other are equal. Adjacent angles add to 180°.','If one angle at a crossing is 70°, its vertically opposite angle is 70°.','Vertically opposite to 70° is …',['110°','90°','70°'],2,'Vertically opposite angles are equal.'],
['A transversal','A transversal crosses two lines. When the lines are parallel, corresponding angles are equal and alternate interior angles are equal.','Railway tracks crossed by a straight road form equal corresponding angles.','For parallel lines, corresponding angles are …',['Equal','Always 90°','Always 180°'],0,'Parallel lines give equal corresponding angles.']
],'Draw two parallel lines and a transversal. Mark an angle of 60° and find the other seven angles.');
add('math','Triangles & Their Properties',[
['Angle sum','The three interior angles of any triangle add to 180°. An exterior angle equals the sum of the two opposite interior angles.','If two angles are 50° and 60°, the third is 180 − 110 = 70°.','Third angle with 50° and 60°?',['110°','70°','80°'],1,'180 − 50 − 60 = 70°.'],
['Triangle inequality','The sum of any two sides must be greater than the third side. Otherwise the sides cannot meet to form a triangle.','Sides 2, 3 and 6 cannot form a triangle: 2 + 3 is less than 6.','Which lengths form a triangle?',['2, 3, 6','1, 2, 3','3, 4, 5'],2,'Each pair sum exceeds the remaining side for 3, 4, 5.'],
['Right triangles','In a right triangle, the square of the hypotenuse equals the sum of squares of the other two sides. The hypotenuse is opposite 90°.','For legs 3 and 4, hypotenuse² = 9 + 16 = 25, so hypotenuse = 5.','A right triangle with legs 3 and 4 has hypotenuse …',['5','7','12'],0,'3² + 4² = 5².']
],'Draw an isosceles triangle with vertex angle 40°. Calculate both base angles.');
add('math','Congruent Triangles',[
['Same shape and size','Congruent triangles fit exactly on each other. Their matching sides and matching angles are equal.','Two triangular tiles made from the same mould are congruent.','Congruent triangles have …',['Same shape only','Same shape and size','Equal area only'],1,'Congruence requires exactly matching shape and size.'],
['SSS and SAS','SSS uses three matching side lengths. SAS uses two sides and the angle between them. The included angle matters.','Two sides 4 cm and 5 cm with included angle 60° fix a triangle.','SAS requires the angle …',['Opposite any side','To be 90°','Between the two known sides'],2,'The angle must be included between the given sides.'],
['ASA and RHS','ASA uses two angles and their included side. RHS works for right triangles with equal hypotenuse and one equal corresponding leg.','Two right-angle brackets with equal longest side and one equal leg have congruent triangular profiles.','RHS applies to …',['Right triangles','Every quadrilateral','Only equilateral triangles'],0,'RHS means right angle, hypotenuse, side.']
],'Trace a triangle and cut a second identical copy. Rotate one: do they remain congruent? Explain.');
add('math','Construction of Triangles',[
['Three sides','For SSS construction, draw one side. Draw arcs from its endpoints using the other side lengths. Their intersection gives the third vertex.','To draw sides 4, 5, 6 cm, start with 6 cm and intersect arcs of radii 4 and 5 cm.','The third vertex in SSS construction comes from …',['A guessed point','Intersecting arcs','A midpoint every time'],1,'The arcs enforce both remaining side lengths.'],
['Two sides and an angle','For SAS, draw a side, construct the included angle at its endpoint, mark the second side along the ray, then join the free endpoints.','A 5 cm side, 60° included angle and 4 cm side specify one triangle up to congruence.','Where is the SAS angle placed?',['Between the given sides','At any vertex','Outside only'],0,'It must be the angle included between those sides.'],
['Check the drawing','Measure your completed sides and angles. A neat sketch first helps identify which measurements belong together.','A construction with angles 70° and 60° must have a third angle of 50°.','Third angle for 70° and 60°?',['60°','70°','50°'],2,'180 − 70 − 60 = 50°.']
],'Use a ruler and compass to construct a triangle with sides 5 cm, 5 cm and 6 cm. Label the vertices.');
add('math','Perimeter & Area',[
['Boundary and surface','Perimeter measures the boundary in units of length. Area measures the surface in square units. For a rectangle: P = 2(l + b), A = l × b.','A 5 m by 3 m garden needs 16 m of fencing and covers 15 m².','Area of a 5 m by 3 m rectangle?',['16 m²','15 m²','8 m²'],1,'Area = 5 × 3 = 15 m².'],
['Triangles and parallelograms','Triangle area = 1/2 × base × perpendicular height. Parallelogram area = base × perpendicular height. A slant side is not necessarily the height.','A triangle with base 8 cm and height 5 cm has area 20 cm².','Triangle area for base 8 and height 5?',['40 cm²','13 cm²','20 cm²'],2,'Half of 8 × 5 is 20.'],
['Circles','Circumference = 2πr and area = πr². Diameter = 2r. Use the value of π given in the problem.','With r = 7 cm and π = 22/7, circumference = 44 cm.','Diameter when radius is 7 cm?',['14 cm','7 cm','49 cm'],0,'Diameter is twice the radius.']
],'A room is 4 m by 3 m. How many 1 m² tiles cover it, ignoring gaps and waste? How much skirting is needed?');
add('math','Data Handling',[
['Mean, median and mode','Mean = total ÷ count. Median is the middle value after sorting. Mode is the most frequent value; a set can have more than one mode or none.','For 2, 3, 3, 8: mean = 4, median = 3, mode = 3.','Mean of 2, 3, 3, 8?',['3','4','8'],1,'The total is 16 and there are 4 values: 16/4 = 4.'],
['Charts','Bar graphs compare categories; equally wide bars use a consistent scale. A double bar graph compares two related sets.','Compare favourite sports by counting votes and drawing one bar for each sport.','A bar graph is useful for …',['Comparing categories','Proving all causes','Measuring angles only'],0,'Bar height represents the value for each category.'],
['Chance','For equally likely outcomes, probability = favourable outcomes / total outcomes. It ranges from 0 to 1.','A fair die has three even faces out of six: P(even) = 3/6 = 1/2.','P(even number) on a fair six-sided die?',['1/6','1','1/2'],2,'The even faces are 2, 4 and 6: three out of six.']
],'Record the reading minutes of five days. Calculate mean, median and range, then draw a bar graph.');
add('math','Symmetry & Visualising Solids',[
['Reflection symmetry','A line of symmetry divides a shape into matching mirror halves. A shape may have none, one or several.','A square has four lines of symmetry: two diagonals and two through opposite side midpoints.','How many lines of symmetry does a square have?',['2','4','1'],1,'Both diagonals and both midpoint lines are symmetry lines.'],
['Rotational symmetry','The order is the number of times a shape matches itself in a full 360° turn. A square has order 4.','Turn a square by 90°, 180°, 270° and 360°; it fits each time.','A square has rotational order …',['2','1','4'],2,'It matches four times during one full turn.'],
['Faces, edges and vertices','A face is a flat surface of a polyhedron, an edge joins two faces, and a vertex is a corner. A net unfolds a solid onto a plane.','A cube has 6 faces, 12 edges and 8 vertices.','A cube has how many edges?',['12','8','6'],0,'Count four on top, four below and four connecting them.']
],'Draw a cube net and label its six faces. Explain why a flat square and a cube are different.');

add('science','Nutrition in Plants',[
['Making food','Green plants use light energy to make food from carbon dioxide and water. Chlorophyll helps capture light. This process is photosynthesis and releases oxygen.','A balcony plant needs light and water; its leaves are food-making surfaces.','What supplies energy for photosynthesis?',['Soil','Sunlight','Oxygen'],1,'Light energy drives photosynthesis. Soil supplies water and minerals, not light energy.'],
['Other ways of feeding','A parasite takes nutrients from a living host. Saprotrophs obtain nutrients from dead matter. Insectivorous plants photosynthesise but trap insects for extra nutrients such as nitrogen.','A mushroom grows on decaying matter; Cuscuta takes nutrients from a host plant.','Mushrooms commonly obtain nutrients from …',['Sunlight alone','Plastic','Decaying organic matter'],2,'Fungi often digest dead material externally and absorb nutrients.'],
['Soil nutrients','Plants absorb mineral nutrients through roots. Legume roots can house Rhizobium bacteria that fix nitrogen; this is a helpful partnership.','Growing pulses in crop rotation can improve soil nitrogen availability.','Rhizobium helps by …',['Fixing nitrogen','Making sunlight','Removing every mineral'],0,'These bacteria convert atmospheric nitrogen into forms usable by plants.']
],'Sketch a leaf and add arrows for sunlight, water, carbon dioxide and oxygen. Explain why a plant kept in darkness struggles.');
add('science','Nutrition in Animals & Humans',[
['The digestive journey','Ingestion takes food in. Digestion breaks it into simpler substances. Absorption takes nutrients into blood. Assimilation uses them. Egestion removes undigested matter.','A sandwich travels through mouth, food pipe, stomach, small intestine and large intestine.','Most nutrient absorption happens in the …',['Food pipe','Small intestine','Mouth'],1,'Villi in the small intestine increase surface area for absorption.'],
['Organs working together','Teeth break food physically. Saliva begins starch digestion. The stomach mixes food with acid and enzymes. Bile helps break fat into droplets; it is not an enzyme.','Chewing rice well mixes it with saliva before swallowing.','Saliva begins digestion of …',['Starch','All fats','Bone'],0,'Salivary amylase starts breaking down starch.'],
['Other animals','Ruminants swallow plant food, then regurgitate cud and chew again. Amoeba surrounds food with pseudopodia and digests it in a food vacuole.','A cow chewing while resting is often chewing cud.','Amoeba captures food using …',['Teeth','Wings','Pseudopodia'],2,'Temporary projections surround the food.']
],'Draw the digestive path. At each stop, write one job in your own words.');
add('science','Chemical Substances & Changes',[
['Elements and compounds','An element contains one kind of atom. A compound contains different elements chemically joined in fixed proportions. A mixture is a physical combination.','Iron is an element; water is a compound; salt water is a mixture.','Salt water is a …',['Element','Mixture','Pure compound'],1,'Salt and water are physically combined and can be separated.'],
['Physical and chemical change','A physical change does not make a new substance. A chemical change does. Reversibility alone is not a reliable rule for classifying every change.','Melting ice gives liquid water; rusting makes a new substance on iron.','Which is a chemical change?',['Melting ice','Cutting paper','Rusting iron'],2,'Rust is a new substance formed by a chemical reaction.'],
['Evidence and prevention','Colour change, gas, heat or a precipitate can suggest a reaction, but consider the context. Rusting needs oxygen and moisture. Paint limits contact with them.','A painted bicycle frame resists rust because the coating protects its metal.','Paint prevents rust mainly by …',['Blocking air and moisture','Turning iron into plastic','Adding water'],0,'The barrier limits the reactants reaching the iron.']
],'Compare tearing paper with burning paper conceptually. Identify what changes; do not burn anything yourself.');
add('science','Acids, Bases & Salts',[
['Recognising substances','Acids and bases are groups of substances with different chemical properties. Never taste an unknown substance to identify it.','Lemon juice is acidic; soap solution is usually basic.','Which is commonly acidic?',['Soap solution','Lemon juice','Baking soda solution'],1,'Lemon juice contains citric acid.'],
['Indicators','An indicator changes colour with acidity or basicity. Acids turn blue litmus red; bases turn red litmus blue. Neutral solutions do neither.','Litmus can identify an acidic liquid without tasting it.','An acid turns blue litmus …',['Blue','Green','Red'],2,'Blue litmus becomes red in acidic conditions.'],
['Neutralisation','An acid reacting with a base commonly produces salt and water. Many such reactions release heat. “Salt” is a chemical class, not just table salt.','An antacid can reduce excess stomach acidity; medicines should be used with an adult and medical guidance.','Acid + base commonly gives …',['Salt and water','Only oxygen','Only sugar'],0,'This is the standard neutralisation pattern.']
],'Make a table of safe familiar acids and bases from labels or textbooks. Do not mix cleaning chemicals.');
add('science','Heat & Temperature',[
['Two related ideas','Temperature tells how hot or cold something is. Heat is energy transferred because of a temperature difference, from hotter to colder objects.','A hot cup loses energy to the cooler room until temperatures become closer.','Heat naturally flows from …',['Colder to hotter','Hotter to colder','Small to large only'],1,'The temperature difference determines the natural direction.'],
['Three routes','Conduction transfers energy through material without bulk movement. Convection involves moving fluids. Radiation needs no material medium.','A metal spoon warms by conduction, boiling water circulates by convection, and the Sun warms Earth by radiation.','The Sun warms Earth mainly by …',['Conduction','Convection','Radiation'],2,'Radiation travels across space without a material medium.'],
['Insulation','Good insulators slow heat transfer. Trapped air is an effective insulator. Use a suitable thermometer; do not handle hot objects for experiments without an adult.','A woollen sweater traps air and slows the loss of body heat.','Wool keeps us warm mainly because it …',['Slows heat loss','Makes sunlight','Produces fire'],0,'Trapped air reduces transfer of heat from our body.']
],'Explain why a cooking pan may have a metal body and an insulated handle.');
add('science','Motion & Time',[
['Speed','Speed = distance / time. Average speed uses total distance and total time. Units must match: metres per second or kilometres per hour.','A bicycle travels 12 km in 2 hours: average speed = 6 km/h.','12 km in 2 hours gives speed …',['24 km/h','6 km/h','10 km/h'],1,'12 divided by 2 is 6.'],
['Uniform motion','Uniform motion covers equal distances in equal times. Real journeys can vary in speed even when their average is easy to calculate.','A car stopping at signals has non-uniform motion.','A car stopping at traffic signals has …',['Always uniform motion','No time','Non-uniform motion'],2,'Its speed changes and may become zero at stops.'],
['Graphs and clocks','On a distance–time graph, a steeper straight line means greater speed. A horizontal distance line indicates rest. A pendulum repeats oscillations.','If distance remains 20 m for 5 seconds, the object has not moved farther.','A horizontal distance–time graph means …',['Rest','Increasing speed','Moving backwards necessarily'],0,'Distance stays unchanged with time.']
],'Time a safe walking route. Estimate average speed and explain why it differs from speed at every moment.');
add('science','Respiration in Organisms',[
['Breathing versus respiration','Breathing moves air in and out. Cellular respiration releases usable energy from food. With oxygen, glucose produces carbon dioxide and water.','After running, your cells need more energy and your breathing rate increases.','Respiration mainly …',['Moves bones directly','Releases energy from food','Creates sunlight'],1,'Cells break down food to release energy for activities.'],
['Air exchange','During inhalation the chest cavity expands; during exhalation it gets smaller. Gas exchange occurs across thin surfaces in the lungs.','Put a hand on your chest while breathing gently; notice the movement.','During inhalation the chest cavity …',['Shrinks','Stays sealed','Expands'],2,'Expansion helps air enter the lungs.'],
['Different organisms','Fish use gills, insects have tracheal tubes and earthworms exchange gases through moist skin. Plants respire too, day and night.','A fish takes dissolved oxygen from water with its gills.','Fish obtain oxygen using …',['Gills','Feathers','Leaves'],0,'Gills provide surfaces for exchange with water.']
],'Compare breathing and respiration in two columns. Include where each happens and what each does.');
add('science','Transport in Plants & Animals',[
['Blood circulation','The heart pumps blood through vessels. Arteries carry blood away from the heart; veins carry it toward the heart. Capillaries connect them.','The heartbeat you feel reflects pumping that transports oxygen and nutrients.','Arteries carry blood …',['Always without oxygen','Away from the heart','Only to the brain'],1,'Direction from the heart defines an artery; oxygen content has exceptions.'],
['Blood and waste','Red blood cells carry oxygen using haemoglobin. White blood cells help defend the body. Platelets help clotting. Kidneys filter wastes from blood to form urine.','A small cut stops bleeding partly because a clot forms.','Blood clotting involves …',['Root hairs','Bile','Platelets'],2,'Platelets help begin formation of a clot.'],
['Plant transport','Xylem carries water and minerals, mainly upward from roots. Phloem moves food from leaves to parts that need it. Transpiration is water-vapour loss, mainly through stomata.','Water absorbed at roots reaches leaves through xylem.','Water moves through plants mainly in …',['Xylem','Phloem only','Petals'],0,'Xylem transports water and mineral nutrients.']
],'Trace a drop of water from soil to leaf. Explain how this differs from movement of food.');
add('science','Reproduction in Plants',[
['Seeds and flowers','Stamens produce pollen; the pistil includes stigma, style and ovary. After fertilisation, ovules develop into seeds and the ovary commonly develops into fruit.','A mango fruit protects the seed formed after reproduction.','Ovules develop into …',['Leaves','Seeds','Pollen'],1,'Following fertilisation, ovules become seeds.'],
['Pollination and fertilisation','Pollination transfers pollen to the stigma. Fertilisation joins male and female gametes. They are different steps.','A bee can carry pollen between flowers; the gametes join later.','Pollination is …',['Joining gametes','Making roots','Transferring pollen to stigma'],2,'It is pollen transfer, not fertilisation itself.'],
['Asexual reproduction','One parent can form new plants through vegetative propagation, budding or spores. Potato tuber buds can grow into new plants.','A potato eye is a bud that can produce a plant.','A potato commonly propagates through …',['Tuber buds','Feathers','Animal eggs'],0,'The eyes on its tuber are buds.']
],'Draw a labelled flower. Use two different arrow labels to distinguish pollination from fertilisation.');
add('science','Soil',[
['Layers','Soil develops through weathering and organic processes. Topsoil usually contains more humus and living organisms than deeper layers.','Leaf litter decomposes and adds organic matter to the upper soil.','Humus is mainly …',['Plastic','Decayed organic matter','Solid metal'],1,'Humus comes from decomposition of plant and animal remains.'],
['Texture and water','Sandy soil has larger particles and usually drains quickly. Clay holds water strongly. Loam combines particle sizes and often supports plants well.','A pot of sandy soil drains faster than a clay-rich pot under similar conditions.','Which usually drains fastest?',['Clay-rich soil','All soils equally','Sandy soil'],2,'Large spaces between sand grains allow faster drainage.'],
['Conservation','Roots hold soil. Vegetation, careful irrigation and contour practices help reduce erosion. Topsoil takes a long time to form.','A grass-covered slope loses less soil during rain than a bare one.','Plant roots reduce …',['Soil erosion','All rainfall','Earth’s rotation'],0,'Roots bind soil and vegetation slows flowing water.']
],'Explain why removing plants from a slope can affect a stream below it.');
add('science','Light',[
['Straight paths','Light travels in straight lines through a uniform transparent medium. An opaque object blocks it and can form a shadow.','A book blocks a torch beam and casts a shadow.','An opaque object …',['Transmits all light','Blocks light','Always makes its own light'],1,'Opaque materials do not allow light to pass through them.'],
['Reflection','Reflection is light bouncing from a surface. A plane mirror gives an upright virtual image of the same size, at equal distance behind the mirror.','If you stand 1 m from a flat mirror, your image appears 1 m behind it.','A plane-mirror image is usually …',['Always upside down','Twice as large','Same size as the object'],2,'A plane mirror preserves image size.'],
['Curved mirrors and lenses','Concave mirrors curve inward; convex mirrors bulge outward and give a wider field of view. Convex lenses can converge light; concave lenses diverge it.','A vehicle mirror is often convex to show a wider area. Never focus sunlight toward eyes or flammable material.','A wide-view vehicle mirror is commonly …',['Convex','Plane only','Concave only'],0,'Convex mirrors give a wider field of view with smaller upright images.']
],'Compare a shadow with a mirror image. Include colour detail, formation and whether it shows your face.');
add('science','Electric Current & Its Effects',[
['Closed circuits','Current flows around a complete conducting path connected to a source. Opening a switch breaks the circuit.','A torch turns off when its switch creates a gap in the path.','Current in a simple circuit needs …',['An open gap','A closed conducting path','No source'],1,'A complete path allows charge to flow.'],
['Heating effect','Current can heat a conductor. Heating appliances use this effect. A fuse melts when excessive current heats it sufficiently.','A fuse protects a circuit by breaking it when current becomes too high.','A fuse protects by …',['Adding more current','Making water','Melting and breaking the circuit'],2,'Melting interrupts the path. Never bypass a fuse.'],
['Magnetic effect','A current-carrying coil can behave like a magnet. Adding a suitable iron core strengthens an electromagnet; it can be switched off.','An electric bell uses the magnetic effect of current. Use only safe low-voltage school kits, never mains wiring.','An electromagnet is made magnetic by …',['Electric current','Paint','Sound only'],0,'Current in the coil produces a magnetic field.']
],'Draw a battery, bulb and switch in a closed circuit. Draw the open-switch version beside it.');
add('science','Weather, Climate & Adaptation',[
['Different time scales','Weather is the atmospheric condition at a place over a short time. Climate describes long-term patterns, usually assessed over decades.','Rain today is weather; a region’s typical wet monsoon is part of its climate.','Today’s temperature describes …',['Climate only','Weather','Earth’s core'],1,'It is a short-term condition.'],
['Adaptations','An adaptation is a trait that helps an organism survive and reproduce in its environment, developed across generations. It is not a quick deliberate choice.','A polar bear’s fur and fat reduce heat loss in a cold environment.','Thick fur in polar animals helps …',['Create ice','Stop breathing','Reduce heat loss'],2,'It insulates the body in cold conditions.'],
['Habitats','Different habitats present different challenges. Tropical rainforests have high rainfall and rich biodiversity; deserts require water conservation.','A camel conserves water; its hump stores fat rather than liquid water.','A camel’s hump mainly stores …',['Fat','Water','Air'],0,'The hump stores fat that can be used as an energy reserve.']
],'Choose one desert and one polar animal. Connect each adaptation to the problem it helps solve.');
add('science','Winds, Storms & Safety',[
['Pressure differences','Moving air is wind. Uneven heating creates pressure differences, and air tends to move from higher toward lower pressure.','Land heats faster than sea during the day; cooler sea air can move toward land.','Air tends to move from …',['Low to high pressure','High to low pressure','No direction ever'],1,'Pressure differences drive air movement.'],
['Rising warm air','Warm air expands and is generally less dense than cooler air at similar pressure. It rises, helping drive convection and weather systems.','Warm air above heated ground rises and surrounding air moves in.','Warm air generally …',['Always sinks','Turns solid','Rises'],2,'Heating usually reduces its density relative to nearby cooler air.'],
['Storm safety','During lightning, shelter in a substantial building or a fully enclosed hard-top vehicle. Avoid isolated trees and open fields. Follow local alerts during severe storms.','If thunder begins during outdoor play, move indoors promptly.','The safest listed place during lightning is …',['A substantial building','Under a lone tree','An open playground'],0,'An appropriate enclosed shelter is safer than exposed locations.']
],'Write a short family storm-safety plan with shelter, emergency contacts and a way to follow official alerts.');
add('science','Forests & Ecosystems',[
['Connected lives','An ecosystem includes living things and their non-living surroundings. Producers make food; consumers obtain it from other organisms.','Grass → deer → tiger is a simplified food chain.','In that chain, grass is the …',['Top predator','Producer','Decomposer only'],1,'Grass makes food through photosynthesis.'],
['Decomposers','Decomposers break down dead material, returning nutrients to the surroundings. Food webs have many linked chains.','Fungi and bacteria recycle nutrients from fallen leaves.','Decomposers mainly …',['Stop all growth','Create rocks only','Recycle nutrients'],2,'They break down organic matter so nutrients can be reused.'],
['Forest services','Forests support biodiversity, influence the water cycle, store carbon and protect soil. Clearing them affects connected systems.','Roots stabilise soil and leaf cover softens the impact of rainfall.','Forests help protect soil by …',['Holding it with roots','Stopping every river','Removing all insects'],0,'Roots and cover reduce erosion.']
],'Build a food web with five organisms. Predict one effect if an important producer disappears.');
add('science','Water & Wastewater',[
['Water cycle','Evaporation turns liquid into vapour; condensation forms droplets; precipitation returns water to Earth. Collection and infiltration continue the cycle.','Water vapour condenses into tiny droplets in clouds.','Vapour becoming liquid is …',['Evaporation','Condensation','Combustion'],1,'Condensation changes gas into liquid.'],
['Responsible use','Freshwater is limited in accessible supply. Repair leaks, use water carefully and protect water sources from pollution. Clear water is not automatically safe to drink.','A leaking tap wastes water even when no one is using it.','Clear-looking water is …',['Always safe','Always distilled','Not necessarily safe'],2,'Invisible microorganisms or chemicals may still be present.'],
['Treatment','Wastewater treatment removes solids and uses processes including microbes to reduce organic waste. Drinking-water treatment has additional safety requirements.','Screens remove large objects; settling removes heavier solids; aeration supports useful microbes.','Screens first remove …',['Large solid objects','All dissolved salts','Every microbe'],0,'Screens trap large debris, not every dissolved pollutant.']
],'List three ways your family can conserve water. Explain why paint and oil should not enter drains.');
add('science','Fibre to Fabric',[
['Sources','Fibres are strands used to make yarn and fabric. Cotton comes from plants, wool mainly from fleece, and silk from silkworm cocoons.','A cotton T-shirt and a woollen sweater use fibres from different sources.','Silk comes from …',['Cotton seeds','Silkworm cocoons','Sheep fleece'],1,'Silkworms spin cocoons with silk fibres.'],
['Wool processing','Wool production commonly involves shearing, cleaning, sorting, dyeing and spinning. Cleaning removes dirt and grease from fleece.','Raw fleece must be cleaned before becoming yarn.','Cleaning raw fleece is called …',['Weaving','Pollination','Scouring'],2,'Scouring removes grease and dirt.'],
['Yarn to fabric','Spinning makes yarn from fibres. Weaving interlaces two sets of yarn; knitting makes loops from yarn.','A knitted scarf has looped stitches; woven cloth has crossing threads.','Weaving means …',['Interlacing yarn sets','Growing fibres','Melting wool'],0,'Warp and weft yarns interlace to make woven fabric.']
],'Inspect clothing labels and classify three garments by fibre source. Compare how their fabrics feel.');
add('social','Environment & Earth’s Spheres',[
['Four connected spheres','The lithosphere is solid land, hydrosphere is water, atmosphere is air and biosphere includes living organisms. They interact constantly.','Rain from the atmosphere enters soil and supports a plant in the biosphere.','The hydrosphere includes …',['Only air','Water','Only animals'],1,'Hydro refers to water, including oceans, rivers and ice.'],
['Natural and human environments','Natural surroundings include mountains and rivers. Human-made features include buildings and roads. People depend on and change nature.','A bridge is human-made but crosses a natural river.','Which is human-made?',['Mountain','River','Bridge'],2,'A bridge is designed and built by people.'],
['Balance','Actions in one sphere can affect others. Pollution and habitat change can damage the systems that sustain life.','Cutting vegetation can increase erosion and muddy nearby water.','Removing vegetation can increase …',['Soil erosion','Root growth everywhere','Ocean salinity instantly'],0,'Without roots and cover, soil is more easily carried away.']
],'Map five things around your home to Earth’s spheres. Show one connection between two spheres.');
add('social','Inside Earth: Rocks & Minerals',[
['Earth’s layers','Earth has a thin crust, a thick mantle and a core. The outer core is liquid and the inner core is solid. The mantle is mostly solid but can flow slowly over long times.','Think of an egg as a rough layer analogy, but Earth is not literally an egg.','The outermost solid layer is the …',['Core','Crust','Mantle'],1,'The crust forms Earth’s outer solid surface.'],
['Rock types','Igneous rocks form when molten material cools. Sedimentary rocks form from deposited material. Metamorphic rocks change under heat and pressure without fully melting.','Granite is igneous; sandstone is sedimentary; marble is metamorphic.','Marble is commonly …',['Sedimentary','Igneous','Metamorphic'],2,'Limestone can change into marble under heat and pressure.'],
['Rock cycle','Weathering, erosion, deposition, heat, pressure, melting and cooling connect rock types over geological time.','A rock breaks into particles that later become part of a sedimentary rock.','Molten rock cooling produces …',['Igneous rock','Paper','Humus only'],0,'Solidification of molten material forms igneous rock.']
],'Compare the three rock types using their formation processes and one example each.');
add('social','Changing Landforms',[
['Internal and external forces','Internal processes include tectonic movement and volcanism. External processes include weathering, erosion and deposition.','An earthquake changes land suddenly; a river reshapes it over time.','River erosion is an …',['Internal process only','External process','Astronomical process'],1,'Water acts on Earth’s surface.'],
['Rivers at work','A river erodes, transports and deposits material. Waterfalls, meanders, floodplains and deltas form in different conditions.','A delta grows where a river deposits sediment near its mouth.','A delta forms mainly by …',['Melting','Earthquakes','Deposition'],2,'Sediment settles where the river loses carrying power.'],
['Wind, ice and waves','Wind moves sand; glaciers carve valleys; waves erode cliffs and deposit beaches. Landforms depend on the agent and conditions.','Sand dunes grow where wind deposits sand.','Sand dunes commonly result from …',['Wind deposition','Volcanoes only','Ocean tides only'],0,'Wind transports sand and deposits it into dunes.']
],'Draw a river from mountains to sea and label a waterfall, meander and delta in suitable locations.');
add('social','Air, Weather & Climate',[
['Atmosphere','The atmosphere is the blanket of gases around Earth. Nitrogen is most abundant; oxygen is next. Weather occurs mainly in the troposphere.','Clouds and most rain form in the lowest atmospheric layer.','Most weather occurs in the …',['Core','Troposphere','Inner mantle'],1,'The troposphere contains most atmospheric water vapour and weather.'],
['Temperature and pressure','Sunlight heats Earth unevenly. Temperature, pressure, wind, humidity and rainfall describe weather. Higher altitude usually has cooler air in the troposphere.','A hill station can be cooler than nearby lowlands.','Humidity measures …',['Rock size','Road length','Water vapour in air'],2,'Humidity describes the moisture content of air.'],
['Climate patterns','Climate is a long-term pattern rather than one day’s condition. Latitude, altitude, distance from sea and circulation influence it.','Coastal places often have less extreme temperatures than inland places.','Climate describes …',['Long-term patterns','Only today’s rain','One gust of wind'],0,'Climate uses conditions observed over long periods.']
],'Keep a five-day weather diary and explain why it cannot by itself establish the climate.');
add('social','Water Around Earth',[
['Oceans and freshwater','Most Earth water is saline ocean water. Much freshwater is in ice or underground, and only a small part is readily available in rivers and lakes.','The sea cannot usually be used directly as drinking water.','Most Earth water is …',['River water','Saline ocean water','Rain in clouds'],1,'Oceans contain the vast majority of Earth’s water.'],
['Waves, tides and currents','Waves often form from wind. Tides are periodic sea-level changes caused mainly by Moon and Sun gravity. Currents are sustained movements of seawater.','A beach may have high and low tide at different times.','Tides are mainly related to …',['Streetlights','Trees','Moon and Sun gravity'],2,'Their gravitational effects contribute to tidal patterns.'],
['Ocean influence','Ocean currents move heat and affect coastal climates and marine life. Water circulates between ocean, air and land through the water cycle.','Warm currents can influence temperatures along nearby coasts.','Currents can transport …',['Heat','Only rocks','No energy'],0,'Moving water carries thermal energy.']
],'Explain the difference between a wave, a tide and an ocean current in your own words.');
add('social','Vegetation, Wildlife & Human Habitats',[
['Climate and plants','Temperature and moisture influence vegetation. Tropical forests, grasslands and deserts have different plant communities.','A cactus reduces water loss in dry conditions.','Vegetation is strongly influenced by …',['Phone brands','Temperature and moisture','School uniforms'],1,'These conditions affect plant survival and growth.'],
['Settlements','Settlements are places where people live. Water, jobs, safety, land and transport influence their location and growth.','A town may grow near a river and a railway junction.','A reliable water supply can …',['Stop every settlement','Remove all trade','Support settlement growth'],2,'People need water for daily life and livelihoods.'],
['Transport and communication','Transport moves people and goods; communication shares information. Both connect places, but access can be unequal.','A train transports a parcel; a phone message tells the recipient it is coming.','A phone message is primarily …',['Communication','Physical transport','Mining'],0,'It transfers information rather than the parcel itself.']
],'Describe how life in a desert settlement differs from life beside a large river. Connect each difference to conditions.');
add('social','Studying the Medieval Past',[
['Sources','Historians use inscriptions, coins, manuscripts, buildings and other evidence. Each source has a context and may be incomplete or biased.','A coin can show a ruler’s title but does not describe everyone’s daily life.','A coin is a …',['Weather forecast','Historical source','Complete story of all people'],1,'Coins provide evidence that must be interpreted with other sources.'],
['Changing meanings','Place names, language and boundaries change. Use terms in their historical context and compare different sources.','A name used in a medieval text may cover a different area from the same name today.','Historical terms should be understood through …',['Modern guesses only','One advertisement','Their context'],2,'Meaning can change over time and between authors.'],
['Chronology','Chronology places events in time order. Centuries help organise long periods; the 13th century covers 1201–1300.','The year 1250 belongs to the 13th century.','1250 is in the …',['13th century','12th century','15th century'],0,'Years 1201–1300 form the 13th century.']
],'Choose an old object in your family. State what it reveals and one thing it cannot tell you.');
add('social','Regional Kingdoms & the Delhi Sultanate',[
['Regional power','Medieval regional kingdoms grew through agriculture, resources, military power and alliances. Temples could also be centres of economic and cultural life.','The Cholas developed administration and irrigation in southern India.','Irrigation supported kingdoms mainly through …',['Less farming','Agricultural production','No settlements'],1,'Reliable water helped agriculture and revenue.'],
['The Sultanate','The Delhi Sultanate began in the early 13th century and had several dynasties. Its rulers needed administration, revenue and armies to govern changing territories.','Qutb-ud-din Aibak was an early ruler of the Delhi Sultanate.','The Delhi Sultanate began in the early …',['18th century','7th century','13th century'],2,'Its establishment is commonly dated to 1206.'],
['Administration','Officials and military leaders managed assigned territories and revenue. Control depended on communication, resources and local conditions.','Distant territories were harder to supervise than nearby ones.','A major challenge of large kingdoms was …',['Managing distant territories','Avoiding all records','Having no agriculture'],0,'Distance made communication and supervision difficult.']
],'Make a timeline with the beginning of the Delhi Sultanate and the Mughal Empire. Add two questions a historian might investigate.');
add('social','The Mughal Empire & Regional States',[
['Beginning','Babur defeated Ibrahim Lodi at the First Battle of Panipat in 1526. This marked the beginning of Mughal rule in India.','A timeline can place 1526 before Akbar’s rule.','The First Battle of Panipat was in …',['1757','1526','1857'],1,'Babur’s victory in 1526 established Mughal power.'],
['Governance','Akbar used officials, revenue arrangements and alliances to expand and administer the empire. Mansabdars held ranked positions with service obligations.','A mansab indicated rank in Mughal service.','A mansab was connected to …',['A rainfall scale','A type of cloth','Rank and service'],2,'Mansabdars were ranked officials with duties.'],
['Regional states','As Mughal central power weakened, regional states gained autonomy. The process varied by region; it was not a single overnight change.','Awadh, Bengal and Hyderabad developed stronger regional authority in the 18th century.','Regional states grew as …',['Central Mughal power weakened','All farming stopped','Every city vanished'],0,'Changing power relations allowed regional rulers greater autonomy.']
],'Explain how alliances can help a ruler govern, and how they can also create dependencies.');
add('social','Culture, Faith & Communities',[
['Bhakti traditions','Bhakti traditions emphasised devotion in different forms. Many poet-saints used regional languages and questioned social divisions. Their teachings were diverse.','Kabir’s poetry encouraged reflection beyond narrow divisions.','Regional languages helped teachings …',['Stay inaccessible','Reach more people','Become only tax records'],1,'People could understand teachings in familiar languages.'],
['Sufi traditions','Sufi traditions emphasised spiritual practice and devotion. Khanqahs could be centres of teaching, hospitality and community life.','Visitors gathered at Sufi centres for guidance and fellowship.','A khanqah was associated with …',['A shipyard','A volcano','Sufi community life'],2,'It was a place connected to Sufi teaching and practice.'],
['Cultural exchange','Trade, migration, patronage and local creativity shaped music, architecture, languages and art. Cultures are dynamic, not isolated.','A building can combine artistic influences from several regions.','Cultural exchange can occur through …',['Trade and migration','No contact at all','Only weather'],0,'Contact between communities carries ideas and practices.']
],'Choose one monument or art form and identify two influences that helped shape it. Verify facts in your textbook.');
add('social','Democracy, Equality & State Government',[
['Equality','Democracy rests on political equality and participation. Equality before law means people should receive equal legal protection without unfair discrimination.','A public facility should serve people without excluding them because of caste or religion.','Equality before law means …',['Identical hobbies','Equal legal protection','Only wealthy people can complain'],1,'The law should protect people equally.'],
['Representation','Citizens elect MLAs to state legislative assemblies. A government is formed according to the constitutional system and assembly support.','An MLA represents a constituency in the state assembly.','An MLA serves in the …',['Supreme Court as judge','Village school only','State legislative assembly'],2,'MLA means Member of the Legislative Assembly.'],
['Accountability','People can question representatives, use lawful participation and seek information. Public debate and oversight help accountability.','Citizens can ask officials about an unfinished public road.','Accountability means officials should …',['Explain and answer for decisions','Never face questions','Ignore all laws'],0,'Public authority comes with responsibility to explain actions.']
],'Write three respectful questions you would ask an elected representative about a local public service.');
add('social','Media, Advertising & Markets',[
['Media literacy','Media shares information and shapes discussion. Compare sources, check evidence and distinguish fact from opinion. Ownership and advertising can affect priorities.','A viral message is not proof; check the original source and date.','Before sharing a claim, you should …',['Trust its popularity','Check evidence and source','Remove the date'],1,'Popularity does not establish accuracy.'],
['Advertisements','Advertisements persuade people to buy or support something. Branding can influence choices. Ask whether claims are supported and compare actual cost and need.','A “best ever” slogan gives no measurable evidence by itself.','An advertisement primarily aims to …',['Guarantee every claim','Replace all news','Persuade'],2,'It tries to influence a choice or attitude.'],
['Markets and work','Markets connect buyers and sellers. A product may pass through producers, wholesalers and retailers; bargaining power and earnings differ.','A shirt’s price includes more than the fabric: labour, transport and retail costs matter.','A wholesaler usually …',['Deals in larger quantities','Only buys one item for home','Makes all laws'],0,'Wholesalers commonly buy and sell goods in bulk.']
],'Compare two advertisements for the same type of item. Separate facts, opinions and missing information.');

add('english','Articles, Nouns & Pronouns',[
['Articles','Use a/an for a non-specific singular countable noun and the for something identifiable. Choose a or an by the initial sound, not just the letter.','An hour begins with a vowel sound; a university begins with a “y” sound.','Choose the correct phrase.',['A hour','An hour','The a hour'],1,'The h is silent in “hour”, so use an.'],
['Nouns','Nouns name people, places, things or ideas. Proper nouns name particular people or places and usually begin with a capital letter.','“Delhi” is proper; “city” is common; “courage” is abstract.','Which is a proper noun?',['City','Courage','Delhi'],2,'Delhi names a particular city.'],
['Pronouns','Pronouns can replace nouns, but their reference should be clear. Choose forms that fit their role: she as subject, her as object.','“Riya reads. She enjoys stories.” She refers to Riya.','Choose: “___ enjoys stories.”',['She','Her','Hers'],0,'The sentence needs the subject form “she”.']
],'Write five sentences about your school using a, an and the. Underline two nouns and replace one with a suitable pronoun.');
add('english','Sentences & Clauses',[
['A complete thought','A sentence normally needs a subject and a finite verb and must express a complete thought. Fragments leave essential information unfinished.','“Because it rained” is unfinished on its own; “We stayed inside because it rained” is complete.','Which is a complete sentence?',['Because it rained.','We stayed inside.','After the bell.'],1,'It has a subject, a finite verb and a complete thought.'],
['Compound sentences','A compound sentence joins independent clauses, often with and, but or or. Each clause can stand alone.','“I studied, but I still needed practice.” Both parts make complete sentences.','“I studied, but I needed practice” is …',['A word','A fragment','A compound sentence'],2,'Two independent clauses are joined by but.'],
['Complex sentences','A complex sentence includes an independent clause and at least one dependent clause. Words such as because, although and when can introduce dependence.','“Although it rained, we reached school.” The first clause depends on the second.','Which introduces a dependent clause?',['Although','Notebook','Quickly'],0,'Although introduces a clause that cannot stand alone here.']
],'Write one simple, one compound and one complex sentence about the same school event.');
add('english','Tenses & Subject–Verb Agreement',[
['Time and aspect','Tenses help show time and how an action unfolds. Present simple often describes habits; present continuous describes activity happening now.','“I read every day” is a habit; “I am reading now” is happening now.','Choose for “right now”:',['I read every day','I am reading','I reads'],1,'Present continuous fits an action in progress.'],
['Agreement','A singular third-person subject usually takes an -s verb in present simple. A plural subject usually does not.','“She plays”; “They play”. Do not make the verb agree with an unrelated nearby noun.','Choose the correct sentence.',['They plays.','She play.','She plays.'],2,'A singular third-person subject takes plays.'],
['Past and future','Simple past describes a completed past event. Future reference can use will, be going to and other forms depending on meaning.','“We visited yesterday.” “We are going to visit tomorrow.”','Choose for yesterday.',['We visited.','We visits.','We will visit.'],0,'Visited places the event in the past.']
],'Write three sentences about yesterday, three about usual habits and three about plans for tomorrow.');
add('english','Verbs, Modals & Reported Speech',[
['Transitive verbs','A transitive verb takes a direct object. An intransitive use does not. The same verb can have different uses.','“She opened the door”: the door is the object. “The door opened”: no direct object.','In “She opened the door”, the object is …',['She','The door','Opened'],1,'The door receives the action.'],
['Modals','Modals express meanings such as ability, permission, advice and obligation. Use the base verb after a modal.','“You should revise” gives advice; “You can swim” expresses ability.','Choose the correct form.',['She can swims.','She can swimming.','She can swim.'],2,'A modal is followed by the base form of the verb.'],
['Reporting words','Reported speech conveys someone’s message without copying the exact words. Pronouns, time words and tenses may change with context.','Riya said, “I am tired.” Later: Riya said that she was tired.','In this report, “I” becomes …',['She','You always','They always'],0,'The pronoun refers to Riya, so she is appropriate.']
],'Report three things a friend said yesterday. Check pronouns and time expressions, and explain any tense changes.');
add('english','Reading Stories & Poetry',[
['Evidence-based reading','Identify characters, setting, events and conflict. A theme is a larger idea supported by the text; a summary retells the main events briefly.','If a character helps a rival despite difficulty, kindness may be a theme. Quote or paraphrase the supporting action.','A theme is …',['Every event in order','A larger idea supported by the text','Only the title'],1,'Theme concerns the meaning explored through the text.'],
['Inference','An inference combines textual clues with reasoning. Distinguish what the text states from what you conclude.','“Meera’s hands shook before the speech” suggests nervousness, though it does not directly say so.','From shaking hands before a speech, Meera may be …',['Definitely asleep','Definitely dishonest','Nervous'],2,'The clue reasonably supports nervousness, though context matters.'],
['Poetic devices','A simile compares using like or as. A metaphor makes a direct comparison. Personification gives human qualities to non-human things.','“The wind whispered” personifies wind; “as bright as a star” is a simile.','“The wind whispered” uses …',['Personification','An instruction','A date'],0,'Whispering gives the wind a human-like action.']
],'Use a poem from your DAV book. Explain one image and one central idea with evidence. This module teaches skills; it does not replace your assigned literature text.');
add('english','Writing Notices, Letters & Stories',[
['Notice writing','A notice communicates an event briefly. Include the organisation, NOTICE, date, clear heading, essential details and name/designation, following your school’s format.','For a book fair, mention what, when, where and whom to contact.','An event notice should clearly include …',['Only a slogan','Date, time and venue','An unrelated ending'],1,'Readers need practical details to act on the notice.'],
['Formal communication','Formal letters and emails need a clear purpose, polite language, relevant details and suitable closing. Avoid unclear requests and unnecessary repetition.','“Please repair the leaking tap near Room 7” is more useful than “Something is wrong”.','A formal request should be …',['Insulting','Vague','Specific and polite'],2,'A precise request helps the reader understand the action needed.'],
['Story structure','Plan a setting, characters, problem, developing events and a satisfying ending. Use details and dialogue that serve the story. Revise for clarity.','A lost library book can lead to a search, a clue and a thoughtful resolution.','A story conflict is the …',['Central problem','Writer’s address','Page number'],0,'Conflict creates the challenge that drives events.']
],'Write an 80–100 word notice or a 150-word story. Check your school’s expected format, punctuation and completeness.');

add('hindi','संज्ञा, सर्वनाम और विशेषण',[
['संज्ञा','किसी व्यक्ति, स्थान, वस्तु या भाव के नाम को संज्ञा कहते हैं। व्यक्तिवाचक संज्ञा खास नाम बताती है; जातिवाचक संज्ञा एक वर्ग बताती है।','“दिल्ली” खास स्थान है, “शहर” एक वर्ग है और “ईमानदारी” भाव है।','भाववाचक संज्ञा कौन-सी है?',['कुर्सी','ईमानदारी','दिल्ली'],1,'ईमानदारी एक भाव या गुण का नाम है।'],
['सर्वनाम','संज्ञा के स्थान पर आने वाले शब्द सर्वनाम हैं। संदर्भ साफ रखें ताकि पता चले कि वह या वे किसके लिए है।','“रीना पढ़ती है। वह मेहनती है।” यहाँ वह, रीना के लिए है।','“वह” किस शब्द-भेद का उदाहरण है?',['विशेषण','क्रिया','सर्वनाम'],2,'वह किसी नाम के स्थान पर इस्तेमाल हो सकता है।'],
['विशेषण','संज्ञा या सर्वनाम की विशेषता बताने वाला शब्द विशेषण कहलाता है। वह गुण, संख्या या मात्रा बता सकता है।','“लाल फूल” में लाल, फूल का रंग बताता है।','“लाल फूल” में विशेषण है …',['लाल','फूल','दोनों संज्ञा हैं'],0,'लाल शब्द फूल की विशेषता बताता है।']
],'अपने कमरे के बारे में पाँच वाक्य लिखिए। संज्ञाओं के नीचे रेखा और विशेषणों के चारों ओर घेरा बनाइए।');
add('hindi','क्रिया, काल और वाक्य',[
['क्रिया','काम करने या होने का बोध कराने वाले शब्द क्रिया हैं। वाक्य में कर्ता और क्रिया का संबंध समझें।','“बच्ची खेलती है” में खेलती है क्रिया है।','“रवि दौड़ता है” में क्रिया है …',['रवि','दौड़ता है','केवल रवि'],1,'दौड़ता है कार्य का बोध कराता है।'],
['काल','काल से कार्य का समय पता चलता है: वर्तमान, भूत और भविष्य। पूरे क्रिया-रूप को देखकर समय पहचानें।','“मैं गया” भूतकाल है; “मैं जाऊँगा” भविष्यकाल है।','“मैं कल जाऊँगा” में काल है …',['भूतकाल','वर्तमानकाल','भविष्यकाल'],2,'जाऊँगा भविष्य में होने वाले कार्य को बताता है।'],
['वाक्य की स्पष्टता','वाक्य में शब्दों का क्रम, लिंग-वचन का मेल और विराम चिह्न अर्थ को स्पष्ट बनाते हैं।','“लड़कियाँ पढ़ती हैं” में बहुवचन कर्ता के अनुसार क्रिया है।','सही वाक्य चुनिए।',['लड़कियाँ पढ़ती हैं।','लड़कियाँ पढ़ता है।','लड़कियाँ पढ़ती है।'],0,'बहुवचन के लिए पढ़ती हैं सही रूप है।']
],'आज, कल और बीते दिन के बारे में दो-दो वाक्य लिखिए। क्रिया और काल पहचानिए।');
add('hindi','शब्द-भंडार और मुहावरे',[
['पर्यायवाची और विलोम','पर्यायवाची शब्दों के अर्थ मिलते-जुलते हैं। विलोम शब्द विपरीत अर्थ देते हैं। सही शब्द संदर्भ के अनुसार चुनें।','जल और पानी पर्यायवाची हैं; दिन और रात विलोम हैं।','“दिन” का विलोम है …',['सूर्य','रात','सुबह'],1,'दिन और रात विपरीत समय-स्थितियाँ बताते हैं।'],
['मुहावरे','मुहावरे का अर्थ शब्दों के सीधे अर्थ से अलग होता है। उसे पूरा समझकर उपयुक्त वाक्य में प्रयोग करें।','“आँखों का तारा” का अर्थ बहुत प्रिय व्यक्ति है।','“आँखों का तारा” का अर्थ है …',['आकाश का तारा','आँख का रोग','बहुत प्रिय'],2,'यह प्रेम और प्रियता बताने वाला मुहावरा है।'],
['शब्द-निर्माण','उपसर्ग शब्द के पहले और प्रत्यय उसके बाद जुड़कर अर्थ बदलते हैं। हर शब्द को मनमाने ढंग से नहीं तोड़ना चाहिए।','सु + गंध = सुगंध; सुंदर + ता = सुंदरता।','“सुंदरता” में प्रत्यय है …',['ता','सु','सुंदर'],0,'ता अंत में जुड़कर भाववाचक शब्द बनाता है।']
],'तीन मुहावरे चुनकर ऐसे वाक्य बनाइए जिनसे उनका अर्थ स्पष्ट हो।');
add('hindi','अपठित गद्यांश और साहित्य-पठन',[
['मुख्य विचार','गद्यांश पढ़कर उसका मुख्य विचार पहचानें। उत्तर केवल अपनी सामान्य जानकारी से नहीं, दिए गए पाठ के आधार पर दें।','यदि पूरा अनुच्छेद पानी बचाने के उपाय बताता है, तो मुख्य विचार जल संरक्षण होगा।','मुख्य विचार पहचानने के लिए देखें …',['केवल पहला अक्षर','पूरा पाठ किस विषय पर केंद्रित है','केवल कठिन शब्द'],1,'मुख्य विचार पूरे पाठ की केंद्रीय बात है।'],
['अनुमान और प्रमाण','पाठ के संकेतों से अनुमान लगाएँ और उसके लिए शब्द या घटना का प्रमाण दें। अनुमान को निश्चित तथ्य न मानें।','“वह पुरस्कार देखकर मुस्कुराई” से प्रसन्नता का अनुमान हो सकता है।','अनुमान के साथ देना चाहिए …',['असंबंधित कहानी','केवल शीर्षक','पाठ का प्रमाण'],2,'प्रमाण उत्तर को पाठ से जोड़ता है।'],
['कविता और भाव','कविता में भाव, बिंब और शब्द-चयन पर ध्यान दें। पंक्तियों का अर्थ सरल भाषा में बताइए, केवल शब्द बदलकर नहीं।','प्रकृति-वर्णन में वर्षा का बिंब आशा या ताजगी व्यक्त कर सकता है; संदर्भ देखें।','भावार्थ लिखते समय …',['मुख्य भाव सरल भाषा में बताएँ','केवल शब्द गिनें','पाठ की उपेक्षा करें'],0,'भावार्थ कविता का आशय स्पष्ट करता है।']
],'अपने ज्ञान सागर के एक पाठ का संक्षिप्त सार और दो प्रमाण-आधारित उत्तर लिखिए। पाठ उपलब्ध होने पर अध्याय-विशिष्ट सामग्री जोड़ी जा सकती है।');
add('hindi','अनुच्छेद, पत्र और संवाद',[
['अनुच्छेद','एक केंद्रीय विषय चुनें। परिचय, जुड़े हुए विचार और उपयुक्त समापन रखें। अनावश्यक दोहराव हटाएँ।','“स्वच्छ विद्यालय” में समस्या, उपाय और विद्यार्थियों की भूमिका को क्रम से लिखें।','अच्छे अनुच्छेद में विचार …',['बिना संबंध के होते हैं','एक केंद्रीय विषय से जुड़े होते हैं','केवल एक शब्द होते हैं'],1,'विषय से जुड़ाव स्पष्टता देता है।'],
['पत्र','औपचारिक पत्र में पता, दिनांक, संबोधन, विषय, स्पष्ट निवेदन और उपयुक्त समापन रखें। विद्यालय का निर्धारित प्रारूप मानें।','छुट्टी का आवेदन कारण और अवधि स्पष्ट बताता है।','छुट्टी के आवेदन में जरूरी है …',['केवल कहानी','केवल कविता','कारण और अवधि'],2,'पाठक को अनुरोध का कारण और समय जानना चाहिए।'],
['संवाद','संवाद पात्रों की बातचीत है। भाषा स्वाभाविक और परिस्थिति के अनुकूल रखें। हर वक्ता की बात अलग दिखाएँ।','पुस्तकालय में छात्र और पुस्तकालयाध्यक्ष के बीच किताब माँगने की बातचीत।','संवाद में स्पष्ट होना चाहिए …',['कौन बोल रहा है','केवल पृष्ठ संख्या','केवल लेखक का पता'],0,'वक्ता की पहचान बातचीत समझने में मदद करती है।']
],'पुस्तकालय में पुस्तक लौटाने पर छह पंक्तियों का संवाद लिखिए।');

add('sanskrit','शब्दरूप: Nouns & Agreement',[
['Three grammatical genders','Sanskrit nouns have grammatical gender: masculine, feminine or neuter. Learn gender with the noun rather than guessing from English meaning.','बालकः is masculine, बालिका is feminine, and फलम् is neuter.','फलम् is …',['Masculine','Neuter','Feminine'],1,'फलम् is a neuter noun.'],
['Three numbers','Sanskrit uses singular, dual and plural. Dual is specifically for two. Endings vary with gender, stem and case.','बालकः = one boy; बालकौ = two boys; बालकाः = boys, more than two.','बालकौ refers to …',['One boy','Many boys','Two boys'],2,'The ending here is nominative dual.'],
['Nominative forms','For the masculine अ-stem बालक, nominative forms are बालकः, बालकौ, बालकाः. Learn complete tables with meanings and uses.','बालकः पठति means “the boy reads”.','Choose the singular subject.',['बालकः','बालकौ','बालकाः'],0,'बालकः is nominative singular.']
],'Write nominative singular, dual and plural for बालक and connect each to one, two or many. Use your book for full assigned शब्दरूप tables.');
add('sanskrit','धातुरूप: Present-Tense Verbs',[
['Roots and verbs','A धातु is a verb root. पठ् means read; गम् means go. लट् forms commonly express present time.','पठति means “he/she reads”; गच्छति means “he/she goes”.','पठति means …',['Writes','Reads','Sleeps'],1,'The root पठ् expresses reading.'],
['Person and number','The verb agrees with the subject in person and number. In Sanskrit naming, प्रथमपुरुष corresponds to third person, मध्यमपुरुष to second and उत्तमपुरुष to first.','सः पठति; त्वं पठसि; अहं पठामि.','With अहम्, use …',['पठति','पठसि','पठामि'],2,'अहम् means I and takes first-person singular पठामि.'],
['Dual and plural','For third-person present of पठ्: पठति, पठतः, पठन्ति match singular, dual and plural subjects.','बालकौ पठतः means “the two boys read”.','With बालकौ, use …',['पठतः','पठति','पठामि'],0,'A dual third-person subject needs पठतः.']
],'Create three short sentences using अहम्, त्वम् and सः. Check each verb ending.');
add('sanskrit','Cases, Pronouns & Simple Translation',[
['Subject and object','Case endings signal roles. Nominative often marks the subject; accusative often marks the direct object. Word order can vary.','बालकः फलम् खादति = the boy eats a fruit. बालकः is subject; फलम् is object.','In this sentence, the subject is …',['फलम्','बालकः','खादति'],1,'बालकः names the person doing the action.'],
['Pronouns','Pronouns replace nouns and must match context. सः means he/that masculine, सा means she/that feminine, तत् can mean it/that neuter.','सा पठति = she reads.','सा commonly means …',['I','You','She'],2,'सा is feminine nominative singular.'],
['Translation steps','Find the verb first, then the subject and other roles using endings. Translate the whole meaning rather than isolated words only.','अहं विद्यालयं गच्छामि = I go to school.','गच्छामि means …',['I go','He reads','They eat'],0,'It is first-person singular present of गम्.']
],'Translate सः पठति, सा लिखति and अहं विद्यालयं गच्छामि. Identify the subject and verb in each.');
add('sanskrit','Vocabulary, Reading & Numbers',[
['Familiar words','Learn vocabulary through small meaningful groups such as home, school and nature. Repeat words in short sentences.','जलम् = water; पुस्तकम् = book; विद्यालयः = school.','जलम् means …',['Book','Water','School'],1,'जलम् is the Sanskrit word for water.'],
['Numbers','Learn numbers with their noun forms. Some Sanskrit number words change with gender and case, so a list alone is not enough.','एकम् फलम् = one fruit; दश = ten.','दश means …',['Five','Two','Ten'],2,'दश denotes ten.'],
['Reading for meaning','Read a sentence slowly, identify familiar roots and endings, and use context. Retell the meaning in simple English or Hindi.','In बालकः पुस्तकम् पठति, the boy is reading a book.','पुस्तकम् means …',['Book','Water','House'],0,'पुस्तकम् names a book.']
],'Create ten vocabulary cards from your assigned Sanskrit chapter. Add meaning and one short example, checked against your book.');
add('computer','Computer Evolution & Digital Systems',[
['Generations','Computers evolved through technologies including vacuum tubes, transistors, integrated circuits and microprocessors. Smaller components helped improve size and efficiency.','A modern laptop packs components that once needed far more space.','An integrated circuit contains …',['Only paper','Many electronic components on a chip','A water tank'],1,'An IC combines electronic components into a compact device.'],
['Hardware and software','Hardware is physical equipment. Software is instructions and programs. Input enters data; processing works on it; output presents results; storage keeps it.','A keyboard is hardware; a word-processing program is software.','Which is software?',['Keyboard','Screen','Word-processing program'],2,'A program consists of instructions.'],
['Files and folders','Files hold data; folders organise files. Useful names and backups help you find and protect work. A filename extension often suggests format.','Science-notes.pdf is easier to identify than an unrelated name.','A folder primarily …',['Organises files','Adds RAM physically','Removes every virus'],0,'Folders group and organise files.']
],'Draw an input–process–output example for calculating marks. Identify the hardware and software involved.');
add('computer','Scratch: Events & Sequences',[
['Sprites and stage','A sprite is an object or character that can run scripts. The stage is its scene. Coordinates locate sprites.','A cat sprite can move across a stage when its script runs.','A Scratch sprite is …',['Only a file folder','An object with scripts','A physical keyboard'],1,'Sprites are programmable objects in a Scratch project.'],
['Events','An event starts an action. The green-flag event often begins a project; key-press and click events can trigger specific scripts.','When the green flag is clicked, a sprite can say “Hello”.','Which can start a script?',['An unconnected comment','No event ever','A green-flag event'],2,'The event block triggers the attached sequence.'],
['Sequences','Instructions run in a defined order. Changing order can change behaviour. Test small sequences before expanding them.','Move 10 steps, turn 90°, move 10 steps draws a different path from moving twice before turning.','A sequence means …',['An ordered set of steps','Random steps only','Only an image'],0,'Order determines how the instructions are executed.']
],'In Scratch, make a sprite greet the learner and move when a key is pressed. Explain each block’s role.');
add('computer','Scratch: Loops, Conditions & Variables',[
['Loops','Loops repeat steps. A fixed-repeat loop runs a chosen number of times; forever continues until stopped.','Repeat 4 times: move 50 steps and turn 90°. This traces a square.','Four turns of 90° total …',['90°','360°','180°'],1,'4 × 90° = 360°.'],
['Conditions','A condition is true or false. An if block runs its steps only when the condition is true. If–else chooses between two paths.','If touching the edge, bounce. Otherwise keep moving.','An if block runs its steps when its condition is …',['Always absent','A picture','True'],2,'It checks the condition before executing the enclosed steps.'],
['Variables','A variable stores a value that can change. Initialise it so each new game begins correctly.','Set score to 0 at the start; change score by 1 when an item is collected.','At a new game, score should usually be …',['Reset to its starting value','Left from last game accidentally','Deleted from every project'],0,'Initialisation makes repeated games predictable.']
],'Design a collecting game with a score variable and one if condition. Predict what happens before running it.');
add('computer','Internet, Web Services & Safety',[
['Internet and web','The internet connects networks. The web is a service of linked pages accessed through browsers. A browser and a search engine are different.','A browser opens a website; a search engine helps find pages.','A browser is used to …',['Measure temperature','Open web pages','Build physical cables only'],1,'Browsers display and interact with web content.'],
['Services','Email, cloud storage and video calls use network services. Share files carefully and check recipients and permissions.','A view-only link lets someone read a document without editing it.','View-only permission usually allows …',['Editing all files','Deleting the owner’s account','Reading without editing'],2,'It restricts changes while allowing access to view.'],
['Privacy and security','Use strong unique passwords, avoid sharing personal information publicly and tell a trusted adult about suspicious messages. Never share an OTP with an unexpected caller.','A message claiming a prize may be phishing if it asks for passwords or payment.','What should you do with a suspicious prize link?',['Pause and ask a trusted adult','Enter your password','Share your OTP'],0,'Verification helps avoid phishing and unsafe disclosure.']
],'Create a five-rule online-safety poster. Include privacy, passwords and how to get adult help.');
add('computer','Spreadsheets, Presentations & Images',[
['Cells and formulas','A spreadsheet organises data into rows and columns. A cell address combines column and row. Formulas often begin with =.','A1 is column A, row 1. =SUM(A1:A3) adds those cells.','A1 refers to …',['Row A, column 1','Column A, row 1','All files'],1,'The letter names the column and the number names the row.'],
['Clear presentations','A slide should communicate one main idea with readable text and relevant visuals. Use your own explanations and credit sources.','A science slide with one labelled diagram is easier to follow than a page of tiny text.','A helpful slide uses …',['Tiny text everywhere','Unrelated images','Readable text and relevant visuals'],2,'Clarity supports understanding.'],
['Image editing','Cropping changes the visible area. Resizing changes dimensions. Keep an original copy and check permissions before sharing someone’s photo.','Crop empty edges from a photo while keeping its subject.','Cropping mainly changes …',['The visible area','The camera’s battery','The file’s author automatically'],0,'Cropping removes outer portions of an image.']
],'Make a three-slide explanation of a topic you learned. Add one source credit and check readability.');

add('moral','Integrity & Responsibility',[
['Honesty','Honesty means giving accurate information and owning mistakes. It helps others trust us and makes problems easier to repair.','If you break a classroom item, tell the teacher and help resolve it.','After accidentally breaking an item, a responsible action is …',['Blame someone else','Tell the truth and help repair the problem','Hide it'],1,'Owning the mistake supports trust and repair.'],
['Commitments','Responsibility includes keeping reasonable promises, doing your part and communicating when you need help.','If your group task is delayed, inform your teammates early.','When you cannot finish your group work on time …',['Disappear','Invent a false excuse','Explain early and agree on a plan'],2,'Communication lets the group adjust fairly.'],
['Reflection','Think about who is affected by your action and what a fair next step would be. Good intentions do not erase consequences.','Returning a lost wallet protects its owner from worry and loss.','Before deciding, consider …',['Effects on others','Only how to avoid being caught','Only popularity'],0,'Ethical reflection includes the people affected.']
],'Write about a small mistake and a fair way to make it right. Keep personal details private.');
add('moral','Empathy, Respect & Service',[
['Empathy','Empathy means trying to understand another person’s feelings and perspective. Ask respectfully rather than assuming.','A new student may feel lonely; invite them to join and ask what they enjoy.','An empathetic response is …',['Mocking feelings','Listening and asking kindly','Ignoring everyone'],1,'Listening helps understand a person’s experience.'],
['Respectful disagreement','You can disagree with an idea while respecting the person. Give reasons, listen and avoid insults.','“I see it differently because…” keeps discussion focused on the issue.','When disagreeing, you should …',['Attack the person','Spread rumours','Explain reasons respectfully'],2,'Respectful reasoning allows constructive disagreement.'],
['Service','Service helps meet a real need. Ask what support is useful; respect dignity and safety. Small consistent acts matter.','Help organise shared books rather than doing a project only for praise.','Useful service begins by …',['Understanding the need','Seeking praise only','Making assumptions'],0,'Listening ensures the help actually fits the need.']
],'Plan one safe act of kindness at school. Describe the need, your action and how you will know it helped.');
add('moral','Thoughtful Living & DAV Values',[
['Learning with reflection','Reflective learning means asking questions, examining evidence and improving your understanding. Discuss your assigned Naitik Shiksha text with a teacher.','When a claim puzzles you, ask for its meaning and supporting reasons.','Thoughtful learning involves …',['Never asking questions','Asking and reflecting','Memorising without meaning only'],1,'Questions and reflection deepen understanding.'],
['Community and inclusion','Care for your community includes cooperation and respecting different backgrounds. Shared work should give everyone a fair chance to participate.','Rotate group duties instead of excluding a quieter student.','An inclusive group should …',['Exclude quieter members','Assign all work to one person','Give everyone a fair opportunity'],2,'Participation and fair duties support belonging.'],
['Daily practice','Values are strengthened through repeated choices: truthfulness, discipline, care for nature and responsible conduct. This is a skills module, not a replacement for prescribed religious or biographical lessons.','A daily habit of returning shared materials shows care for others.','Values become practical through …',['Everyday actions','Slogans alone','Avoiding every task'],0,'Consistent behaviour turns principles into practice.']
],'Choose a value from your DAV Moral Education chapter. Describe one action that demonstrates it at home and one at school.');
add('gk','India: Geography & Culture',[
['Places and landscapes','Learn locations through maps rather than isolated lists. India has mountains, plains, plateaus, deserts, coasts and islands.','The Himalayas lie to the north; the Thar Desert lies mainly in the northwest.','The Thar is primarily a …',['Rainforest','Desert','Glacier'],1,'The Thar is a major desert region.'],
['Cultural diversity','India has many languages, foods, art forms and traditions. Avoid assuming every person in a region follows the same custom.','Different regions have distinct musical and dance traditions.','Cultural diversity means …',['Everyone has identical customs','Only one art exists','Many traditions coexist'],2,'Diversity includes different traditions and identities.'],
['Learning carefully','Distinguish the national anthem, Jana Gana Mana, from the national song, Vande Mataram. Learn their context respectfully.','A quiz may ask about these separately.','India’s national anthem is …',['Jana Gana Mana','Vande Mataram','Any film song'],0,'Jana Gana Mana is the national anthem.']
],'On a map, identify your state and three different physical features. Add one cultural fact you have verified.');
add('gk','World, Science & Environment',[
['Maps and directions','A globe represents Earth in three dimensions. Maps flatten it and use symbols, scale and directions. Most standard maps place north at the top, but check the compass.','A scale helps estimate real distances from a map.','A map scale connects …',['Colours to emotions','Map distance to real distance','Dates to names'],1,'It expresses the relationship between mapped and actual distances.'],
['Space basics','Earth rotates on its axis and revolves around the Sun. Rotation produces day and night; the Moon is Earth’s natural satellite.','A day follows Earth’s rotation rather than a trip around the Sun.','Day and night result mainly from Earth’s …',['Ocean tides','Revolution alone','Rotation'],2,'Different sides face the Sun as Earth rotates.'],
['Biodiversity','Biodiversity is the variety of life. Protecting habitats helps protect species. Extinction is the permanent loss of a species.','A wetland supports many connected plants and animals.','Protecting habitats helps …',['Conserve biodiversity','Guarantee no weather change','Remove all species'],0,'Species depend on suitable places and ecological relationships.']
],'Make five fact cards about Earth and space. Note a reliable source on each card; avoid unverified viral claims.');
add('gk','Logic, Sports & Fact Checking',[
['Patterns','Look for a consistent rule in number and shape sequences. More than one rule may fit a short list, so state your assumption.','2, 4, 8, 16 doubles each time; the next term is 32 under this rule.','Next in the doubling pattern 2, 4, 8, 16?',['18','32','24'],1,'Multiply the previous term by 2.'],
['Sports knowledge','Learn a sport through its aim, basic rules and equipment. Rules and records can change, so verify current facts in an official source.','Chess involves protecting your king and trying to checkmate the opponent’s king.','Checkmate ends a chess game because …',['A pawn is missing','The board is full','The king is in check with no legal escape'],2,'Checkmate is an inescapable check under legal moves.'],
['Current information','For current affairs, check the event date, publisher and evidence. This app’s static facts are not a live news feed.','An old medal tally may be correct for its year but misleading if called “latest”.','Before calling a fact current, check …',['Its date and source','Only its font','Only likes'],0,'Time-sensitive facts require current verification.']
],'Write three verified facts from this week’s child-friendly newspaper. Record the date and source beside each.');
add('marathi','नाम, सर्वनाम आणि विशेषण',[
['नाम','व्यक्ती, वस्तू, ठिकाण किंवा भाव यांच्या नावाला नाम म्हणतात. वाक्यात नाव काय दर्शवते ते पाहा.','“पुणे” हे ठिकाणाचे नाव आणि “पुस्तक” हे वस्तूचे नाव आहे.','नाम कोणते?',['पुस्तक','हळू','सुंदर'],0,'पुस्तक हे वस्तूचे नाव आहे.'],
['सर्वनाम','नामाऐवजी वापरला जाणारा शब्द सर्वनाम आहे. तो कोणासाठी वापरला आहे हे स्पष्ट असावे.','“सीमा वाचते. ती आनंदी आहे.” येथे ती हे सीमेसाठी आहे.','“ती” हे …',['क्रियापद','सर्वनाम','विशेषण'],1,'ती हा नामाऐवजी वापरलेला शब्द आहे.'],
['विशेषण','नामाची विशेषता सांगणारा शब्द विशेषण आहे. रंग, आकार किंवा गुण सांगणारे शब्द यासाठी वापरले जातात.','“मोठे घर” यात मोठे घराची विशेषता सांगते.','“मोठे घर” मध्ये विशेषण …',['घर','दोन्ही नामे','मोठे'],2,'मोठे हा शब्द घराची विशेषता सांगतो.']
],'तुमच्या शाळेबद्दल पाच वाक्ये लिहा. नाम आणि विशेषण ओळखा. This optional foundation module is not a mapped Marathi textbook.');
add('marathi','वाचन आणि लेखन कौशल्य',[
['वाचन','उतारा आधी पूर्ण वाचा. मुख्य विचार आणि तपशील वेगळे ओळखा. उत्तरासाठी उताऱ्यातील आधार शोधा.','पाणी बचतीच्या उताऱ्यात उपाय आणि कारणे ओळखा.','उत्तर लिहिताना आधार घ्यावा …',['फक्त अंदाजाचा','उताऱ्याचा','फक्त शीर्षकाचा'],1,'उताऱ्यातील माहितीवर उत्तर आधारित असावे.'],
['लेखन','एका विषयावर संबंधित विचार क्रमाने लिहा. लहान, स्पष्ट वाक्ये आणि योग्य विरामचिन्हे वापरा.','“माझी शाळा” या विषयात ठिकाण, उपक्रम आणि अनुभव मांडता येतात.','चांगल्या परिच्छेदातील विचार …',['विसंगत असतात','फक्त यादी असतात','विषयाशी संबंधित असतात'],2,'विषयाशी संबंध असल्याने परिच्छेद स्पष्ट होतो.'],
['पुनर्वाचन','लेखनानंतर शब्दलेखन, वाक्यरचना आणि अर्थ तपासा. मोठ्याने वाचल्याने अडखळणारी वाक्ये लक्षात येतात.','वाक्य अपूर्ण वाटल्यास आवश्यक शब्द जोडा.','पुनर्वाचनाने …',['चुका सुधारता येतात','अर्थ नाहीसा होतो','नेहमी पाने वाढतात'],0,'तपासणीमुळे स्पष्टता आणि अचूकता सुधारते.']
],'तुमच्या आवडत्या उपक्रमावर ६०–८० शब्द लिहा. मोठ्याने वाचा आणि दोन सुधारणा करा.');
add('skills','Financial Literacy: Money & Choices',[
['Needs and wants','A need supports essential living or learning; a want adds enjoyment or convenience. Context matters and the same item can have different roles.','School supplies may be a need; an extra decorative cover may be a want.','A basic required school notebook is usually …',['A luxury only','A learning need','An investment guarantee'],1,'It supports required learning activities.'],
['Budgeting','A budget plans income and spending. Set aside savings where possible and keep spending within available money.','With ₹200, spending ₹120 leaves ₹80.','₹200 minus ₹120 leaves …',['₹320','₹120','₹80'],2,'200 − 120 = 80.'],
['Careful comparison','Compare unit prices, total costs and actual usefulness. A discount does not make an unnecessary purchase a need.','A 500 g pack for ₹60 costs ₹120 per kg.','500 g for ₹60 equals …',['₹120 per kg','₹60 per kg','₹30 per kg'],0,'1 kg is twice 500 g, so twice ₹60 is ₹120.']
],'Plan a ₹300 stationery budget with quantities, prices and an amount saved.');
add('skills','Health, Movement & Wellbeing',[
['Balanced routines','A healthy routine includes varied meals, movement, rest and hygiene. No single food can provide everything the body needs.','A meal with grains, pulses, vegetables and other suitable foods offers variety.','A balanced diet needs …',['Only one food','Variety','Only sugary drinks'],1,'Different foods provide different nutrients.'],
['Movement and recovery','Choose enjoyable age-appropriate activity and build skills gradually. Hydration and recovery matter. Stop and seek adult help if an activity causes concerning symptoms.','Walking, dancing and outdoor games can make movement enjoyable.','Before a new demanding activity, it helps to …',['Ignore discomfort','Skip all preparation','Begin gradually and seek guidance'],2,'Gradual practice supports safe skill development.'],
['Emotional wellbeing','Feelings are information, not failures. Use breathing, breaks and supportive conversations. Ask a trusted adult for help when worries feel too heavy.','Before a test, pause, take slow comfortable breaths and start with one manageable question.','If a worry feels overwhelming, …',['Talk to a trusted adult','Hide it forever','Stop all learning permanently'],0,'Support from a trusted person can help you cope and find further help.']
],'Create a realistic weekly routine that includes learning, play and rest. Discuss it with your parent.');
add('skills','Art, Music & Creative Observation',[
['Visual elements','Line, shape, colour, texture, space and value help build an artwork. Observe real objects before drawing details.','A cup can be sketched using an ellipse, curved sides and a handle.','Value in visual art refers to …',['Price only','Lightness and darkness','Song speed'],1,'Value describes how light or dark an area appears.'],
['Rhythm and music','Rhythm organises sound in time. A steady beat is a regular pulse; rhythmic patterns can vary over it.','Clap a steady beat and add a repeated short pattern.','A steady beat is …',['A colour','Always silence','A regular pulse'],2,'It provides a consistent timing reference.'],
['Practice and feedback','Creative work improves through observation, experimentation and revision. Explain your choices rather than aiming only to copy perfectly.','After a sketch, check proportions and revise one area.','Useful feedback should be …',['Specific and constructive','Only insulting','Unrelated to the work'],0,'Specific suggestions guide improvement.']
],'Draw a familiar object and write two sentences about your use of light and shape. Then clap a four-beat rhythm.');
